shell-integration = zsh

theme = srcery

background-opacity = 0.95
background-blur-radius = 10

font-family = Maple Mono Normal NL NF CN
font-family = SauceCodePro Nerd Font Mono
font-size = 16

clipboard-read = allow
clipboard-write = allow

macos-icon = retro
macos-option-as-alt = true

mouse-hide-while-typing = true

window-theme = ghostty
window-padding-x = 6,0

quick-terminal-autohide = false

keybind = cmd+grave_accent=toggle_quick_terminal
keybind = shift+enter=text:\n
